version: '3'
services:
  vuesplash_web:
    build: .
    volumes:
      - ./laravel:/var/www/html/app
    ports:
      - 8081:8081
      - 3000:3000
  vuesplash_database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5434:5432
